### ISSUE TITLE
Difficult to read text

### ISSUE THREAD

**Issue by soumendrak** [abhimm5/Lipipra-font#1]
It is challenging to distinguish between the following letters in the font now.

1. ହ and ନ୍ଦ 
2. ଷ and କ୍ଷ
3. ପ and ଯ 

These are coming like below:

![image](https://github.com/abhimm5/Lipipra-font/assets/10120538/2bd99faa-24ee-4c24-93d5-0def5835006e)

![image](https://github.com/abhimm5/Lipipra-font/assets/10120538/cf891c9e-2d4e-479b-87da-60b57f99dbd0)

![image](https://github.com/abhimm5/Lipipra-font/assets/10120538/f0224b97-21cd-428f-bad9-d6830fd3a2f2)

Please check these.

**Comment by abhimm5** [comment]
Thank you for reporting, it is now corrected.
